version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Checking if aws-cli exist...
      - aws --version
      - echo Checking if python exist...
      - python3 --version
      - echo Check if pip3 exist...
      - pip3 --version
  build:
    commands:  # DO THIS AS A USER NOT AS A ROOT
      - echo Build cfn template started on `date`
      - echo Installing cfn-lint 
      - pip3 install --upgrade pip3 cfn-lint
      - echo validate cfn template
      - cfn-lint testing-infra.yaml  # cfn-lint *.yaml will also work 
      - cfn-lint ACM_certificate.yaml # cfn-lint ACM_certificate.yaml testing-infra.yaml will also work
      - cfn-lint dbInstance.yaml
      - echo package the cfn template
      - aws cloudformation package --template-file testing-infra.yaml --s3-bucket madmadmad1234 --output-template-file output-artifacts.yaml
      - aws cloudformation package --template-file ACM_certificate.json --s3-bucket madmadmad1234 --output-template-file result-artifacts.json
      - aws cloudformation package --template-file dbInstance.yaml --s3-bucket madmadmad1234 --output-template-file dbInstance-artifacts.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    # - testing-infra.yaml
    # - output-artifacts.yaml
    # - ACM_certificate.json
    # - result-artifacts.json
    # - dbInstance.yaml
    # - dbInstance-artifacts.yaml
    - "**/*"
